//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportSchedApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercise
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime ScheduledTime { get; set; }
        public string Userid { get; set; }
        public string ExerciseType { get; set; }
    }
}
